name: Delete Corellium devices

on:
  schedule:
    - cron: '49 5 * * 1-5'
  workflow_dispatch:

env:
  TERM: xterm

jobs:
  corellium-delete:
    name: Delete unauthorized devices [${{ matrix.runner-os-friendly-name }}]
    runs-on: ${{ matrix.runner-os }}
    timeout-minutes: 30
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: ${{ matrix.node_tls_reject_unauthorized }}
    strategy:
      fail-fast: false
      matrix:
        runner-os: [ubuntu-latest, self-hosted]
        include:
          - runner-os: ubuntu-latest
            runner-os-friendly-name: Ubuntu
            api_endpoint_secret_key: CORELLIUM_API_ENDPOINT
            api_token_secret_key: CORELLIUM_API_TOKEN
            node_tls_reject_unauthorized: 1
          - runner-os: self-hosted
            runner-os-friendly-name: macOS
            api_endpoint_secret_key: CORELLIUM_DESKTOP_APPLIANCE_API_ENDPOINT
            api_token_secret_key: CORELLIUM_DESKTOP_APPLIANCE_API_TOKEN
            node_tls_reject_unauthorized: 0
    steps:
      - name: Pull the latest code
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: 24
      - name: Install Corellium CLI
        run: |
          npm ci --no-audit --no-fund
          echo "$(pwd)/node_modules/.bin" >> "${GITHUB_PATH}"
      - name: Log in to Corellium
        run: |
          corellium login \
            --apitoken ${{ secrets[matrix.api_token_secret_key] }} \
            --endpoint ${{ secrets[matrix.api_endpoint_secret_key] }}
      - name: Delete Corellium virtual devices
        env:
          AUTHORIZED_INSTANCES: ${{ vars.AUTHORIZED_INSTANCES }}
        run: |
          source ./src/functions.sh && set -euo pipefail
          delete_unauthorized_devices
