name: Install NPM dependencies

on:
  workflow_dispatch:

jobs:
  bump-deps:
    name: Install NPM deps on self-hosted runner
    runs-on: self-hosted
    steps:
      - name: Run npm install
        run: |
          echo '[+] Updating npm dependencies.'
          npm install
          echo '[+] Updated npm dependencies.'
